config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :ideas, except: [:new]
  resources :comments, only: [:create]

  root 'ideas#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :ideas

  def email_id
    email.split("@")[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    Comment.create(idea_id: params[:idea_id],
                   user_id: current_user.id,
                   content: params[:content])
    redirect_to :back
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]
  before_action :only_owner, only: [:edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
    @idea = Idea.new
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)
    @idea.user_id = current_user.id

    respond_to do |format|
      if @idea.save
        format.html { redirect_to ideas_path, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:post)
    end

    def only_owner
      unless @idea.user_id == current_user.id
        flash[:alert] = 'YOU DONT HAVE PERMISSION'
        redirect_to :back
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= form_for(@idea, class: 'col s12') do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="input-field col s9">
      <i class="material-icons prefix">mode_edit</i>
      <%= f.text_area :post, class: 'materialize-textarea' %>
      <%= f.label :post, 'Type your idea' %><br>
    </div>
    <div class="input-field col s3">
      <button class="btn waves-effect waves-light btn-large" type="submit" name="action">Submit
        <i class="material-icons right">send</i>
      </button>
    </div>
  </div>
<% end %>
<script>
$(function() {
    $('textarea').keypress(function(e) {
      if (e.keyCode == 13 && e.shiftKey) {
        $('form').submit();
        return false;
      }
    });
});
</script>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<%= render 'form' %>

<div class="row">
  <% @ideas.each do |i| %>
    <div class="col s12 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= i.user.email_id %></span>
          <p><%= i.post %></p>
        </div>
        <div class="card-action">
          <%= link_to 'Detail', i %>
          <%= link_to 'Edit', edit_idea_path(i) %>
          <%= link_to 'Delete', idea_path(i), method: 'delete' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<h4><%= @idea.user.email_id %>'s IDEA</h4>
<p>
  <%= @idea.post %>
</p>

<span class="badge"><%= @idea.up %></span>
<span class="badge"><%= @idea.down %></span>

<%= form_tag comments_path do %>
  <div class="row">
    <div class="input-field col s9">
      <i class="material-icons prefix">mode_edit</i>
      <input type="hidden" name="idea_id" value="<%=@idea.id%>">
      <%= text_area_tag :content, nil, class: 'materialize-textarea' %>
      <%= label_tag :content, 'Type you comment' %><br>
    </div>
    <div class="input-field col s3">
      <button class="btn waves-effect waves-light btn-large" type="submit" name="action">Submit
        <i class="material-icons right">send</i>
      </button>
    </div>
  </div>
<% end %>

<ol>
  <% @idea.comments.each do |c| %>
    <li><%= c.user.email_id %> : <%= c.content %></li>
  <% end %>
</ol>



<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ideaboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="/" class="brand-logo">Idea Bulletin Board!</a>
      <ul class="right hide-on-med-and-down">
        <% unless user_signed_in? %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% else %>
          <li><%= current_user.email %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, method: 'delete' %></li>
        <% end %>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a href="#">Sign in</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>

  <footer class="page-footer orange">
    <!--
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Company Bio</h5>
          <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Settings</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
    -->
    <div class="footer-copyright">
      <div class="container">
      Made by <a class="orange-text text-lighten-3" href="http://cycorld.com">cycorld</a>
      </div>
    </div>
  </footer>
<script>
$(function() {
  $(".button-collapse").sideNav();
});
<% if notice %>
  Materialize.toast("<%=notice%>", 4000) // 4000 is the duration of the toast
<% end %>
<% if alert %>
  Materialize.toast("<%=alert%>", 4000) // 4000 is the duration of the toast
<% end %>
</script>
</body>
</html>